import { Surah } from './types';

/**
 * The 114 surahs of the Quran with the standard Hafs ayah counts.
 * Total ayat across all surahs = 6236 (validated in tests).
 */
export const SURAHS: readonly Surah[] = [
  { number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatihah', meaningEn: 'The Opening', ayahCount: 7 },
  { number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', meaningEn: 'The Cow', ayahCount: 286 },
  { number: 3, nameAr: 'آل عمران', nameEn: 'Aal-E-Imran', meaningEn: 'The Family of Imran', ayahCount: 200 },
  { number: 4, nameAr: 'النساء', nameEn: 'An-Nisa', meaningEn: 'The Women', ayahCount: 176 },
  { number: 5, nameAr: 'المائدة', nameEn: "Al-Ma'idah", meaningEn: 'The Table Spread', ayahCount: 120 },
  { number: 6, nameAr: 'الأنعام', nameEn: "Al-An'am", meaningEn: 'The Cattle', ayahCount: 165 },
  { number: 7, nameAr: 'الأعراف', nameEn: "Al-A'raf", meaningEn: 'The Heights', ayahCount: 206 },
  { number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', meaningEn: 'The Spoils of War', ayahCount: 75 },
  { number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', meaningEn: 'The Repentance', ayahCount: 129 },
  { number: 10, nameAr: 'يونس', nameEn: 'Yunus', meaningEn: 'Jonah', ayahCount: 109 },
  { number: 11, nameAr: 'هود', nameEn: 'Hud', meaningEn: 'Hud', ayahCount: 123 },
  { number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', meaningEn: 'Joseph', ayahCount: 111 },
  { number: 13, nameAr: 'الرعد', nameEn: "Ar-Ra'd", meaningEn: 'The Thunder', ayahCount: 43 },
  { number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', meaningEn: 'Abraham', ayahCount: 52 },
  { number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', meaningEn: 'The Rocky Tract', ayahCount: 99 },
  { number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', meaningEn: 'The Bee', ayahCount: 128 },
  { number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', meaningEn: 'The Night Journey', ayahCount: 111 },
  { number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', meaningEn: 'The Cave', ayahCount: 110 },
  { number: 19, nameAr: 'مريم', nameEn: 'Maryam', meaningEn: 'Mary', ayahCount: 98 },
  { number: 20, nameAr: 'طه', nameEn: 'Ta-Ha', meaningEn: 'Ta-Ha', ayahCount: 135 },
  { number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', meaningEn: 'The Prophets', ayahCount: 112 },
  { number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', meaningEn: 'The Pilgrimage', ayahCount: 78 },
  { number: 23, nameAr: 'المؤمنون', nameEn: "Al-Mu'minun", meaningEn: 'The Believers', ayahCount: 118 },
  { number: 24, nameAr: 'النور', nameEn: 'An-Nur', meaningEn: 'The Light', ayahCount: 64 },
  { number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', meaningEn: 'The Criterion', ayahCount: 77 },
  { number: 26, nameAr: 'الشعراء', nameEn: "Ash-Shu'ara", meaningEn: 'The Poets', ayahCount: 227 },
  { number: 27, nameAr: 'النمل', nameEn: 'An-Naml', meaningEn: 'The Ant', ayahCount: 93 },
  { number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', meaningEn: 'The Stories', ayahCount: 88 },
  { number: 29, nameAr: 'العنكبوت', nameEn: 'Al-Ankabut', meaningEn: 'The Spider', ayahCount: 69 },
  { number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', meaningEn: 'The Romans', ayahCount: 60 },
  { number: 31, nameAr: 'لقمان', nameEn: 'Luqman', meaningEn: 'Luqman', ayahCount: 34 },
  { number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', meaningEn: 'The Prostration', ayahCount: 30 },
  { number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', meaningEn: 'The Combined Forces', ayahCount: 73 },
  { number: 34, nameAr: 'سبأ', nameEn: 'Saba', meaningEn: 'Sheba', ayahCount: 54 },
  { number: 35, nameAr: 'فاطر', nameEn: 'Fatir', meaningEn: 'The Originator', ayahCount: 45 },
  { number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', meaningEn: 'Ya-Sin', ayahCount: 83 },
  { number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', meaningEn: 'Those Who Set the Ranks', ayahCount: 182 },
  { number: 38, nameAr: 'ص', nameEn: 'Sad', meaningEn: 'Sad', ayahCount: 88 },
  { number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', meaningEn: 'The Troops', ayahCount: 75 },
  { number: 40, nameAr: 'غافر', nameEn: 'Ghafir', meaningEn: 'The Forgiver', ayahCount: 85 },
  { number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', meaningEn: 'Explained in Detail', ayahCount: 54 },
  { number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', meaningEn: 'The Consultation', ayahCount: 53 },
  { number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', meaningEn: 'The Ornaments of Gold', ayahCount: 89 },
  { number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', meaningEn: 'The Smoke', ayahCount: 59 },
  { number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', meaningEn: 'The Crouching', ayahCount: 37 },
  { number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', meaningEn: 'The Wind-Curved Sandhills', ayahCount: 35 },
  { number: 47, nameAr: 'محمد', nameEn: 'Muhammad', meaningEn: 'Muhammad', ayahCount: 38 },
  { number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', meaningEn: 'The Victory', ayahCount: 29 },
  { number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', meaningEn: 'The Rooms', ayahCount: 18 },
  { number: 50, nameAr: 'ق', nameEn: 'Qaf', meaningEn: 'Qaf', ayahCount: 45 },
  { number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', meaningEn: 'The Winnowing Winds', ayahCount: 60 },
  { number: 52, nameAr: 'الطور', nameEn: 'At-Tur', meaningEn: 'The Mount', ayahCount: 49 },
  { number: 53, nameAr: 'النجم', nameEn: 'An-Najm', meaningEn: 'The Star', ayahCount: 62 },
  { number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', meaningEn: 'The Moon', ayahCount: 55 },
  { number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', meaningEn: 'The Most Merciful', ayahCount: 78 },
  { number: 56, nameAr: 'الواقعة', nameEn: "Al-Waqi'ah", meaningEn: 'The Inevitable', ayahCount: 96 },
  { number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', meaningEn: 'The Iron', ayahCount: 29 },
  { number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadila', meaningEn: 'The Pleading Woman', ayahCount: 22 },
  { number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', meaningEn: 'The Exile', ayahCount: 24 },
  { number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', meaningEn: 'She Who is Tested', ayahCount: 13 },
  { number: 61, nameAr: 'الصف', nameEn: 'As-Saff', meaningEn: 'The Ranks', ayahCount: 14 },
  { number: 62, nameAr: 'الجمعة', nameEn: "Al-Jumu'ah", meaningEn: 'The Congregation', ayahCount: 11 },
  { number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', meaningEn: 'The Hypocrites', ayahCount: 11 },
  { number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', meaningEn: 'The Mutual Disillusion', ayahCount: 18 },
  { number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', meaningEn: 'The Divorce', ayahCount: 12 },
  { number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', meaningEn: 'The Prohibition', ayahCount: 12 },
  { number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', meaningEn: 'The Sovereignty', ayahCount: 30 },
  { number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', meaningEn: 'The Pen', ayahCount: 52 },
  { number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', meaningEn: 'The Reality', ayahCount: 52 },
  { number: 70, nameAr: 'المعارج', nameEn: "Al-Ma'arij", meaningEn: 'The Ascending Stairways', ayahCount: 44 },
  { number: 71, nameAr: 'نوح', nameEn: 'Nuh', meaningEn: 'Noah', ayahCount: 28 },
  { number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', meaningEn: 'The Jinn', ayahCount: 28 },
  { number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', meaningEn: 'The Enshrouded One', ayahCount: 20 },
  { number: 74, nameAr: 'المدثر', nameEn: 'Al-Muddaththir', meaningEn: 'The Cloaked One', ayahCount: 56 },
  { number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', meaningEn: 'The Resurrection', ayahCount: 40 },
  { number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', meaningEn: 'Man', ayahCount: 31 },
  { number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', meaningEn: 'The Emissaries', ayahCount: 50 },
  { number: 78, nameAr: 'النبأ', nameEn: 'An-Naba', meaningEn: 'The Tidings', ayahCount: 40 },
  { number: 79, nameAr: 'النازعات', nameEn: "An-Nazi'at", meaningEn: 'Those Who Drag Forth', ayahCount: 46 },
  { number: 80, nameAr: 'عبس', nameEn: 'Abasa', meaningEn: 'He Frowned', ayahCount: 42 },
  { number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', meaningEn: 'The Overthrowing', ayahCount: 29 },
  { number: 82, nameAr: 'الإنفطار', nameEn: 'Al-Infitar', meaningEn: 'The Cleaving', ayahCount: 19 },
  { number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', meaningEn: 'The Defrauding', ayahCount: 36 },
  { number: 84, nameAr: 'الإنشقاق', nameEn: 'Al-Inshiqaq', meaningEn: 'The Splitting Asunder', ayahCount: 25 },
  { number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', meaningEn: 'The Constellations', ayahCount: 22 },
  { number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', meaningEn: 'The Morning Star', ayahCount: 17 },
  { number: 87, nameAr: 'الأعلى', nameEn: "Al-A'la", meaningEn: 'The Most High', ayahCount: 19 },
  { number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', meaningEn: 'The Overwhelming', ayahCount: 26 },
  { number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', meaningEn: 'The Dawn', ayahCount: 30 },
  { number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', meaningEn: 'The City', ayahCount: 20 },
  { number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', meaningEn: 'The Sun', ayahCount: 15 },
  { number: 92, nameAr: 'الليل', nameEn: 'Al-Layl', meaningEn: 'The Night', ayahCount: 21 },
  { number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', meaningEn: 'The Morning Hours', ayahCount: 11 },
  { number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', meaningEn: 'The Relief', ayahCount: 8 },
  { number: 95, nameAr: 'التين', nameEn: 'At-Tin', meaningEn: 'The Fig', ayahCount: 8 },
  { number: 96, nameAr: 'العلق', nameEn: 'Al-Alaq', meaningEn: 'The Clot', ayahCount: 19 },
  { number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', meaningEn: 'The Power', ayahCount: 5 },
  { number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', meaningEn: 'The Clear Proof', ayahCount: 8 },
  { number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', meaningEn: 'The Earthquake', ayahCount: 8 },
  { number: 100, nameAr: 'العاديات', nameEn: 'Al-Adiyat', meaningEn: 'The Courser', ayahCount: 11 },
  { number: 101, nameAr: 'القارعة', nameEn: "Al-Qari'ah", meaningEn: 'The Calamity', ayahCount: 11 },
  { number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', meaningEn: 'The Rivalry in World Increase', ayahCount: 8 },
  { number: 103, nameAr: 'العصر', nameEn: 'Al-Asr', meaningEn: 'The Declining Day', ayahCount: 3 },
  { number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', meaningEn: 'The Traducer', ayahCount: 9 },
  { number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', meaningEn: 'The Elephant', ayahCount: 5 },
  { number: 106, nameAr: 'قريش', nameEn: 'Quraysh', meaningEn: 'Quraysh', ayahCount: 4 },
  { number: 107, nameAr: 'الماعون', nameEn: "Al-Ma'un", meaningEn: 'The Small Kindnesses', ayahCount: 7 },
  { number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', meaningEn: 'The Abundance', ayahCount: 3 },
  { number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', meaningEn: 'The Disbelievers', ayahCount: 6 },
  { number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', meaningEn: 'The Divine Support', ayahCount: 3 },
  { number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', meaningEn: 'The Palm Fiber', ayahCount: 5 },
  { number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', meaningEn: 'The Sincerity', ayahCount: 4 },
  { number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', meaningEn: 'The Daybreak', ayahCount: 5 },
  { number: 114, nameAr: 'الناس', nameEn: 'An-Nas', meaningEn: 'Mankind', ayahCount: 6 },
] as const;
